<?php

namespace App\Models;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Saldo extends Model
{
    public function getSaldo()
    {
      $result = DB::select(DB::raw("WITH ESTOQUE_PODER3_IMPLANT AS (
        SELECT
        EST.CODEMP,
        EST.CODPROD,
        COUNT(DISTINCT EST.CONTROLE) TOTAL
        FROM TGFEST EST
        INNER JOIN TGFITE ITE ON ITE.CONTROLE = EST.CONTROLE AND ITE.CODEMP = EST.CODEMP
        INNER JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
        AND EST.CODPARC > 0
        AND CAB.CODTIPOPER = 299
        WHERE EST.ESTOQUE = 1
        GROUP BY EST.CODPROD, EST.CODEMP
    ),
    USADOS AS (
        SELECT
	     	EST.CODEMP,
		    EST.CODPROD,
	        COUNT(DISTINCT ITE.CONTROLE) TOTAL
	        FROM TGFITE ITE
            INNER JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
            INNER JOIN TGFEST EST ON EST.CONTROLE = ITE.CONTROLE
	        WHERE
	        CAB.CODTIPOPER IN (901, 902, 999)
	        AND EST.CODPARC > 0
            AND EST.ESTOQUE = 1
	        AND NOT EXISTS (SELECT *  FROM TGFITE ITE2
	        INNER JOIN TGFCAB CAB2 ON CAB2.NUNOTA = ITE2.NUNOTA
	        INNER JOIN TGFEST EST2 ON EST2.CONTROLE = ITE2.CONTROLE
	        WHERE
	        CAB2.CODTIPOPER IN (299, 213)
	        AND EST2.CONTROLE = ITE.CONTROLE
	        AND EST2.AD_CONFERIDO = 'S')
	        GROUP BY EST.CODEMP, EST.CODPROD
	        UNION
	        SELECT
		    EST.CODEMP,
	        EST.CODPROD,
	        COUNT(DISTINCT EST.CONTROLE) TOTAL
	        FROM TGFITE ITE
	        INNER JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
	        INNER JOIN TGFEST EST ON EST.CONTROLE = ITE.CONTROLE
	        WHERE
	        1=1
	        AND CAB.CODTIPOPER IN (299, 213)
	        AND EST.AD_CONFERIDO = 'S'
	        AND EST.CODPARC > 0
	        AND EST.ESTOQUE = 1
	        AND NOT EXISTS
            (SELECT * FROM TGFITE ITE2 INNER JOIN TGFCAB CAB ON CAB.NUNOTA = ITE2.NUNOTA WHERE CAB.CODTIPOPER IN (901, 902, 999) AND ITE2.CONTROLE = ITE.CONTROLE)
	        GROUP BY EST.CODEMP, EST.CODPROD
	),
    ESTOQUE_PODER3_REMESSA AS (
    SELECT DISTINCT
    EST.CODEMP,
    EST.CODPROD,
    COUNT(DISTINCT EST.CONTROLE) TOTAL
    FROM TGFITE ITE
                INNER JOIN TGFEST EST ON ITE.CONTROLE = EST.CONTROLE AND EST.CODEMP = ITE.CODEMP
                INNER JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA AND CAB.CODEMP = ITE.CODEMP
                WHERE
                EST.CODPARC > 0
                AND EST.ESTOQUE = 1
                --AND EST.CODPROD = 3000096
    --			AND CAB.CODTIPOPER IN (299, 1106)
                GROUP BY EST.CODPROD, EST.CODEMP
    ),
    VENCE_PODER3_ANO AS (
    SELECT DISTINCT
    EST.CODEMP,
    EST.CODPROD,
    COUNT(DISTINCT EST.CONTROLE) TOTAL
    FROM TGFITE ITE
                INNER JOIN TGFEST EST ON ITE.CONTROLE = EST.CONTROLE AND EST.CODEMP = ITE.CODEMP
                INNER JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA AND CAB.CODEMP = ITE.CODEMP
                WHERE
                EST.CODPARC > 0
                AND EST.ESTOQUE = 1
                AND EXTRACT( YEAR FROM EST.DTVAL) =  EXTRACT( YEAR FROM CURRENT_DATE)
    --			AND EST.CODPROD = 1000229
    --			AND CAB.CODTIPOPER IN (299, 1106)
                GROUP BY EST.CODPROD, EST.CODEMP
    ),
    VENCE_LOCAL_ANO AS (
    SELECT DISTINCT
    EST.CODEMP,
    EST.CODPROD,
    COUNT(DISTINCT EST.CONTROLE) TOTAL
    FROM TGFITE ITE
                INNER JOIN TGFEST EST ON ITE.CONTROLE = EST.CONTROLE AND EST.CODEMP = ITE.CODEMP
                INNER JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA AND CAB.CODEMP = ITE.CODEMP
                WHERE
                EST.CODPARC = 0
                AND EST.ESTOQUE = 1
                AND EXTRACT( YEAR FROM EST.DTVAL) =  EXTRACT( YEAR FROM CURRENT_DATE)
    --			AND EST.CODPROD = 1000229
    --			AND CAB.CODTIPOPER IN (299, 1106)
                GROUP BY EST.CODPROD, EST.CODEMP
    ),
    ESTOQUE_LOCAL AS (
        SELECT
        EST.CODPARC,
        EST.CODEMP,
        EST.CODPROD,
        COUNT(DISTINCT EST.CONTROLE) TOTAL
        FROM TGFEST EST
        WHERE
        EST.ESTOQUE = 1
        AND EST.CODPARC = 0
        --AND NOT EXISTS (SELECT * FROM TGFEST EST2 WHERE EST2.CONTROLE = EST.CONTROLE AND EST2.CODPARC > 0 AND EST2.ESTOQUE = 1)
        --AND NOT EXISTS (SELECT * FROM TGFEST EST2 WHERE EST2.CONTROLE = EST.CONTROLE AND EST2.CODEMP  = 3 AND EST2.ESTOQUE = 1)
        AND EST.CONTROLE <> '0'
        GROUP BY EST.CODPARC,EST.CODPROD, EST.CODEMP
    ),
    CONSUMO_90 AS (
        SELECT
        EST.CODEMP,
        EST.CODPROD,
        COUNT(DISTINCT EST.CONTROLE) TOTAL
        FROM TGFITE ITE
            INNER JOIN TGFEST EST ON ITE.CONTROLE = EST.CONTROLE
            INNER JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
            WHERE
            ITE.CODCFO IN (5102, 6102, 6108, 5114, 6114, 5910, 6910)
            AND ITE.AD_DTUTIL >= CURRENT_DATE - 90
            AND EST.AD_CONFERIDO = 'S'
            AND EST.CONTROLE = ITE.CONTROLE
            GROUP BY EST.CODPROD, EST.CODEMP
    ),
    PERDA AS (
    SELECT
        EST.CODEMP,
        EST.CODPROD,
        COUNT(DISTINCT EST.CONTROLE) TOTAL
        FROM TGFITE ITE
            INNER JOIN TGFEST EST ON ITE.CONTROLE = EST.CONTROLE
            INNER JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
            WHERE
            CAB.CODTIPOPER in (1199)
            AND EST.CONTROLE = ITE.CONTROLE
            GROUP BY EST.CODPROD, EST.CODEMP
    ),
    FATURADOS_SANKHYA AS (
    SELECT
        EST.CODEMP,
        EST.CODPROD,
        COUNT(DISTINCT EST.CONTROLE) TOTAL
        FROM TGFITE ITE
            INNER JOIN TGFEST EST ON ITE.CONTROLE = EST.CONTROLE
            INNER JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
            WHERE
            ITE.CODCFO IN (5102, 6102, 6108, 5114, 6114, 5910, 6910)
            AND EST.CONTROLE = ITE.CONTROLE
            GROUP BY EST.CODPROD, EST.CODEMP
    )
    SELECT
    PRO.AD_CODEMP,
    REPLACE(PRO.CODPROD, ',', ' ') CODPROD,
    PRO.REFERENCIA,
    GRU.DESCRGRUPOPROD GRUPO,
    GRUPAI.DESCRGRUPOPROD GRUPO_PAI,
    PRO.DESCRPROD, COALESCE((SELECT EL.TOTAL FROM ESTOQUE_LOCAL EL WHERE PRO.CODPROD = EL.CODPROD AND PRO.AD_CODEMP = EL.CODEMP), 0 ) SALDO_LOCAL,
    COALESCE((SELECT EP.TOTAL FROM ESTOQUE_PODER3_REMESSA EP WHERE PRO.CODPROD = EP.CODPROD AND PRO.AD_CODEMP = EP.CODEMP), 0) SALDO_P3,
    COALESCE((SELECT sum(USO.TOTAL) FROM USADOS USO WHERE PRO.CODPROD = USO.CODPROD), 0) USADO,
    COALESCE((SELECT FAT.TOTAL FROM FATURADOS_SANKHYA FAT WHERE PRO.CODPROD = FAT.CODPROD  AND PRO.AD_CODEMP = FAT.CODEMP), 0) FATURADOS,
    COALESCE((SELECT EP.TOTAL FROM ESTOQUE_PODER3_REMESSA EP WHERE PRO.CODPROD = EP.CODPROD AND PRO.AD_CODEMP = EP.CODEMP), 0) -
    COALESCE((SELECT sum(USO_SNK.TOTAL) FROM USADOS USO_SNK WHERE PRO.CODPROD = USO_SNK.CODPROD  AND PRO.AD_CODEMP = USO_SNK.CODEMP), 0) P3_LIQUIDO,
    COALESCE((SELECT USO_90.TOTAL FROM CONSUMO_90 USO_90 WHERE PRO.CODPROD = USO_90.CODPROD  AND PRO.AD_CODEMP = USO_90.CODEMP), 0) CONSUMO_90,
    COALESCE((SELECT LOCAL_VENCE.TOTAL FROM VENCE_LOCAL_ANO LOCAL_VENCE WHERE PRO.CODPROD = LOCAL_VENCE.CODPROD  AND PRO.AD_CODEMP = LOCAL_VENCE.CODEMP), 0) VENCE_LOCAL_ANO_ATUAL,
    COALESCE((SELECT P3_VENCE.TOTAL FROM VENCE_PODER3_ANO P3_VENCE WHERE PRO.CODPROD = P3_VENCE.CODPROD  AND PRO.AD_CODEMP = P3_VENCE.CODEMP), 0) P3_VENCE_ANO_ATUAL,
    COALESCE((SELECT TOTAL FROM PERDA  WHERE PRO.CODPROD = PERDA.CODPROD  AND PRO.AD_CODEMP = PERDA.CODEMP), 0) PERDA
--    COALESCE((SELECT USO_IMP.TOTAL FROM USO_PODER3_IMPLANT USO_IMP WHERE PRO.CODPROD = USO_IMP.CODPROD  AND PRO.AD_CODEMP = USO_IMP.CODEMP), 0) USADO_IMP,
--    COALESCE((SELECT USO_SNK.TOTAL FROM USADOS USO_SNK WHERE PRO.CODPROD = USO_SNK.CODPROD  AND PRO.AD_CODEMP = USO_SNK.CODEMP), 0) +
--    COALESCE((SELECT USO_IMP.TOTAL FROM USO_PODER3_IMPLANT USO_IMP WHERE PRO.CODPROD = USO_IMP.CODPROD  AND PRO.AD_CODEMP = USO_IMP.CODEMP), 0) DIV
    --COALESCE((SELECT EP.TOTAL FROM ESTOQUE_PODER3_REMESSA EP WHERE PRO.CODPROD = EP.CODPROD), 0) - (COALESCE((SELECT USO_SNK.TOTAL FROM USADOS_SANKHYA USO_SNK WHERE PRO.CODPROD = USO_SNK.CODPROD), 0) +
    --COALESCE((SELECT USO_IMP.TOTAL FROM USO_PODER3_IMPLANT USO_IMP WHERE PRO.CODPROD = USO_IMP.CODPROD), 0)) SALDO_LIQ_P3
    FROM TGFPRO PRO
    INNER JOIN TGFGRU GRU ON GRU.CODGRUPOPROD = PRO.CODGRUPOPROD
    INNER JOIN TGFGRU GRUPAI ON GRU.CODGRUPAI  = GRUPAI.CODGRUPOPROD
    WHERE LENGTH(PRO.CODPROD) = 7
    and PRO.AD_CODEMP IN (1,3)
    ORDER BY 1"));

        return $result;
    }

    public function getSaldoRastro(){
        $result = DB::select(DB::raw("WITH USADOS AS (
            SELECT DISTINCT
	        CAB.CODEMP,
			EST.CONTROLE,
			EST.CODPROD
	        FROM TGFITE ITE
	        INNER JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
	        INNER JOIN TGFEST EST ON EST.CONTROLE = ITE.CONTROLE
	        WHERE
	        CAB.CODTIPOPER IN (901, 902, 999)
	        AND EST.ESTOQUE = 1
	        AND EST.CODPARC > 0
	        AND NOT EXISTS (SELECT *  FROM TGFITE ITE2
	        INNER JOIN TGFCAB CAB2 ON CAB2.NUNOTA = ITE2.NUNOTA
	        INNER JOIN TGFEST EST2 ON EST2.CONTROLE = ITE2.CONTROLE
	        WHERE
	        CAB2.CODTIPOPER IN (299, 213)
	        AND EST2.CONTROLE = ITE.CONTROLE
	        AND EST2.AD_CONFERIDO = 'S')
	        UNION
	        SELECT DISTINCT
	        CAB.CODEMP,
			EST.CONTROLE,
			EST.CODPROD   FROM TGFITE ITE
	        INNER JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
	        INNER JOIN TGFEST EST ON EST.CONTROLE = ITE.CONTROLE
	        WHERE
	        1=1
	        AND CAB.CODTIPOPER IN (299, 213)
	        AND EST.AD_CONFERIDO = 'S'
	        AND EST.ESTOQUE = 1
	        AND EST.CODPARC > 0
	        AND NOT EXISTS
            (SELECT * FROM TGFITE ITE2 INNER JOIN TGFCAB CAB ON CAB.NUNOTA = ITE2.NUNOTA WHERE CAB.CODTIPOPER IN (901, 902, 999) AND ITE2.CONTROLE = ITE.CONTROLE)
          )
          SELECT
                  EST.CODEMP,
                  'PROPRIO' PODER,
                  CASE WHEN EST.CODPARC = 0 THEN 0 ELSE PAR.CODPARC  END COD_CLIENTE,
                  CASE WHEN EST.CODPARC = 0 THEN ' ' ELSE PAR.NOMEPARC  END CLIENTE,
                  ' ' REGIAO,
                  REPLACE(PRO.CODPROD, ',', ' ') CODPROD,
                  PRO.REFERENCIA,
                  EST.AD_CONTROLE LOTE,
                  PRO.DESCRPROD,
                  GRU.DESCRGRUPOPROD GRUPO,
                  GRUPAI.DESCRGRUPOPROD GRUPO_PAI,
                  TO_CHAR(EST.DTVAL, 'DD/MM/YYYY') DT_VAL,
                  EST.CONTROLE,
                  ' ' USADO,
                  ' ' ARMAZEM,
                  CAST(EST.DTVAL - CURRENT_DATE AS INTEGER) DIAS_VENC
                  FROM
                  TGFEST EST
                  INNER JOIN TGFPRO PRO ON EST.CODPROD = PRO.CODPROD
                  INNER JOIN TGFGRU GRU ON GRU.CODGRUPOPROD = PRO.CODGRUPOPROD
                  INNER JOIN TGFGRU GRUPAI ON GRU.CODGRUPAI  = GRUPAI.CODGRUPOPROD
                  LEFT JOIN TGFPAR PAR ON EST.CODPARC = PAR.CODPARC
                  WHERE
                  LENGTH(PRO.CODPROD) = 7
                  AND ESTOQUE = 1
--                  AND EST.CODPROD = 3000012
                  AND EST.CODPARC = 0
                  AND EST.CONTROLE <> '0'
          --        AND EST.CONTROLE = '000004463202'
--                  AND NOT EXISTS (SELECT * FROM TGFEST EST2 WHERE EST2.CONTROLE = EST.CONTROLE AND EST2.CODPARC > 0 AND EST2.ESTOQUE = 1)
--                  AND NOT EXISTS (SELECT * FROM TGFEST EST2 WHERE EST2.CONTROLE = EST.CONTROLE AND EST2.CODEMP  = 3 AND EST2.ESTOQUE = 1)
          UNION
          SELECT
                  EST.CODEMP,
                  CASE WHEN EST.CODPARC = 0 THEN 'PROPRIO' ELSE 'TERCEIRO' END PODER,
                  CASE WHEN EST.CODPARC = 0 THEN 0 ELSE PAR.CODPARC  END COD_CLIENTE,
                  CASE WHEN EST.CODPARC = 0 THEN ' ' ELSE PAR.NOMEPARC  END CLIENTE,
                  UFS.UF,
                  REPLACE(PRO.CODPROD, ',', ' ') CODPROD,
                  PRO.REFERENCIA,
                  EST.AD_CONTROLE LOTE,
                  PRO.DESCRPROD,
                  GRU.DESCRGRUPOPROD GRUPO,
                  GRUPAI.DESCRGRUPOPROD GRUPO_PAI,
                  TO_CHAR(EST.DTVAL, 'DD/MM/YYYY') DT_VAL,
                  EST.CONTROLE,
                  CASE
                    WHEN EXISTS (SELECT * FROM USADOS WHERE USADOS.CONTROLE = EST.CONTROLE)
                    THEN 'SIM' ELSE 'NAO' END  USADO ,
                  ' ' ARMAZEM,
                  CAST(EST.DTVAL - CURRENT_DATE AS INTEGER) DIAS_VENC
                  FROM
                  TGFEST EST
                  INNER JOIN TGFPRO PRO ON EST.CODPROD = PRO.CODPROD
                  INNER JOIN TGFGRU GRU ON GRU.CODGRUPOPROD = PRO.CODGRUPOPROD
                  INNER JOIN TGFGRU GRUPAI ON GRU.CODGRUPAI  = GRUPAI.CODGRUPOPROD
                  LEFT JOIN TGFPAR PAR ON EST.CODPARC = PAR.CODPARC
                  INNER JOIN TSICID CID ON CID.CODCID = PAR.CODCID
                  INNER JOIN TSIUFS UFS ON UFS.CODUF = CID.UF
                  LEFT JOIN USADOS ON USADOS.CONTROLE = EST.CONTROLE
                  WHERE
                  LENGTH(PRO.CODPROD) = 7
                  AND ESTOQUE = 1
                  AND EST.CONTROLE <> '0'
          --        AND EST.CONTROLE = '000004463202'
--                  AND EST.CODPROD = 3000012
                  AND EST.CODPARC > 0
                  ORDER BY 2,4
        "));

        // foreach($result as $dado){

        //     $rastro = DB::connection('pgsql2')
        //     ->select(DB::raw("select bf_local armazem from sbf000 s where bf_numseri = '$dado->controle' and bf_filial like '$dado->codemp%' and bf_local in ('10', '20', '01', '50', '99', '30') and d_e_l_e_t_ = ''"));

        //     if(isset($rastro[0]->armazem)) $dado->armazem = $rastro[0]->armazem;
        // }

        return $result;
    }
}
